title: Joshua Joel Cuevas # your name (or website title) here
logo: "/images/selfie2 circle.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Introduction 
  <br>Hi, I'm Josh. A recent graduate with passions in economics, data science, ML and cloud computing.<br>
  <br>"This intersection therefore is the use of AI to organize and create insights from huge data through cloud computing and will be something many companies will likely be incorporating in the future."<br>
  <a href="https://www.linkedin.com/in/joshua-joel-cuevas/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

minima:
  color_scheme: dark
